# Generated by Django 5.0.3 on 2024-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_admin_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Admins',
        ),
        migrations.AlterField(
            model_name='product',
            name='kategoriya',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Audi', 'Audi'), ('Kia', 'Kia'), ('GM', 'GM'), ('Toyota', 'Toyota'), ('Chery', 'Chery'), ('Tesla', 'Tesla'), ('BYD', 'BYD')], max_length=200),
        ),
    ]
